### ISSUE TITLE
Toolbar buttons in window

### ISSUE THREAD

**Issue by bladem** [moberwasserlechner/vaadin-medium-editor#25]
![prueba2](https://cloud.githubusercontent.com/assets/2619246/18907363/abfc6d2a-856b-11e6-9911-f6d2cd70926c.jpg)
I tried to use your component in window. The toolbar is showed behind the current window.

**Comment by moberwasserlechner** [comment]
The windows z-index is set to 10000 by the valo theme. I will overwrite the toolbars z-index by 15000.

This fixes the problem until vaadin or anybody decides that the z-index must be higher than 15000.
